---

- name: create instance_path
  file:
    dest: "{{instance_path}}"
    state: directory
    owner: qemu
    group: qemu

- name: get new file
  get_url:
    dest: "{{ instance_path }}/rhel7.qcow2"
    url: http://192.168.11.1:8120/rhel7.1-guest.qcow2


- include: domains.yml
