---

# - name: Restart Network
#   # Restart the network, sleep 3 seconds, return the
#   # exit code returned by "service network restart".
#   # This is to work-around a glitch in Ansible where
#   # it detects a successful network restart as a failure.
#   command: perl -e 'my $exit_code = system("service network restart"); sleep 3; $exit_code = $exit_code >> 8; exit($exit_code);'



#assume that network intefaces have bridges made for them.
