---
- name: Controller Interface Configuration
  hosts: kvmhost
  max_fail_percentage: 0
  roles:


    - subscription-manager
    - common

    - role: iface
      device: em3
      params:
        type: '"Ethernet"'
        bootproto: '"none"'
        onboot: '"yes"'
        peerdns: '"no"'
        bridge: '"bridge0"'
        mtu: '"9000"'

    - role: iface
      device: bridge0
      params:
        type: '"bridge"'
        onboot: '"yes"'
        peerdns: '"no"'
        bootproto: '"static"'
        ipaddr: '172.17.16.79'
        prefix: '24'
        gateway: '172.17.16.1'
        dns1: '172.17.10.22'
        dns2: '192.168.70.3'

    - role: iface
      device: p4p1
      params:
        type: '"Ethernet"'
        bootproto: '"none"'
        onboot: '"yes"'
        peerdns: '"no"'
        bridge: '"bridge1"'
        mtu: '"9000"'

    - role: iface
      device: bridge1
      params:
        type: '"bridge"'
        onboot: '"yes"'
        peerdns: '"no"'

    - role: iface
      device: p4p2
      params:
        type: '"Ethernet"'
        bootproto: '"none"'
        onboot: '"yes"'
        peerdns: '"no"'
        bridge: '"bridge2"'
        mtu: '"9000"'

    - role: iface
      device: bridge2
      params:
        type: '"bridge"'
        onboot: '"yes"'
        peerdns: '"no"'

    - kvm



# vim:ft=ansible:
