---
- name: register to RHN
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_pass }}"
#    pool: "{{ pool }}"
  tags: sub-mgr

- name: subscribe to pool
  command: subscription-manager attach --pool={{pool}}
  register: result
  changed_when: result.stdout.find('enabled') != -1
  failed_when: '"This unit has already had the subscription matching pool ID" not in result.stdout'


- name: enable repos
  shell: "subscription-manager repos --list-enabled | grep 'Repo ID:   {{ item }}' || subscription-manager repos --enable={{ item }}"
  with_items:
    - rhel-7-server-rpms
  register: result
  changed_when: result.stdout.find('enabled') != -1
  tags: sub-mgr
