---
#- name: copy and load 99-sysctl.conf
#  copy: src=99-sysctl.conf dest=/etc/sysctl.d/99-sysctl.conf owner=root group=root mode=0644 force
#  tags: sysctl

#- name: reload the sysctl file
#  command: sysctl -p /etc/sysctl.d/99-sysctl.conf
#  tags: sysctl

- name: disable NetworkManager
  service: name=NetworkManager state=stopped enabled=no

#- name: start network
  #service: name=network state=started enabled=yes

- name: deploy resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  tags: dns

- name: create /etc/hosts with all nodes
  tags: dns
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].int_if.ipaddr }} {{item}}" state=present
  when: hostvars[item].int_if.ipaddr is defined
  with_items: groups['all']

- name: install kvm
  yum:
    state: present
    name: "{{item}}"
  with_items:
    - libvirt-daemon-kvm
    - qemu-kvm
    - libvirt
    - libguestfs
    - virt-install
    - "bridge-utils"
    - "net-tools"
  tags: kvm

- name: install base rpms
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - openssh-clients
    - ntp
    - bind-utils
    - vim

- name: set selinux policy and mode
  selinux: policy=targeted state=permissive
  tags: selinux

- name: install ntp
  yum: pkg=ntp state=installed
  tags: ntp

- name: configure ntp service
  template: src=ntp.conf.j2 dest=/etc/ntp.conf force=yes
  #notify:
  #  - restart ntpd
  tags: ntp

- name: stop ntpd service to prepare for time synchronization
  service: name=ntpd state=stopped
  when: force_ntpdate == "yes"
  tags: ntp

- name: sync time from ntp servers
  command: ntpdate {{ ntp | join(" ") }}
  when: force_ntpdate == "yes"
  tags: ntp

- name: Set hostname
  command: hostnamectl set-hostname --static --transient {{ inventory_hostname }}
  tags: dns
